apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverdeployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: database-pvc
      
      containers:
        - name: task-pv-container
          image: pvrsaikumar/cs695:dindserver
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - dockerd & python3 server.py & python3 handler.py
          volumeMounts:
            - mountPath: /work/Data
              name: pvc-storage
          ports:
            - containerPort: 31001
            - containerPort: 31000
          securityContext:
            privileged: true